### ISSUE TITLE
undefined property

### ISSUE THREAD

**Issue by rafalohaki** [Jeroenimo02/Discord-Webhook-IP-Logger#2]
php 8.1

Warning: Undefined property: stdClass::$connection_type in /var/task/user/api/Discord.php on line 28

Warning: Undefined property: stdClass::$country in /var/task/user/api/Discord.php on line 35

Warning: Undefined property: stdClass::$countryCode in /var/task/user/api/Discord.php on line 36

Warning: Undefined property: stdClass::$regionName in /var/task/user/api/Discord.php on line 37

Warning: Undefined property: stdClass::$city in /var/task/user/api/Discord.php on line 38

Warning: Undefined property: stdClass::$zip in /var/task/user/api/Discord.php on line 39

Warning: Undefined property: stdClass::$lat in /var/task/user/api/Discord.php on line 40

Warning: Undefined property: stdClass::$lon in /var/task/user/api/Discord.php on line 41

Warning: Undefined property: stdClass::$countryCode in /var/task/user/api/Discord.php on line 45

Deprecated: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /var/task/user/api/Discord.php on line 45

**Comment by Jeroenimo02** [comment]
Hi,

I see that the problem is caused by the IP not being fetched by the IP API. I believe this can happen when you try to run it locally, so for example with IP 127.0.0.1 then the API can't fetch the data, beacuse that isn't a real IP

**Comment by Jeroenimo02** [comment]
I began making a v2 of this project, because I learned a lot since then. But I havent started this project up for a while. I might have found some courage to begin working on it agian ;)
Thanks for sharing this issue

**Comment by rafalohaki** [comment]
i ran it on vercel btw

**Comment by Jeroenimo02** [comment]
Oh strange. Didn't know of Vercel. But I will definitely add some checks so that no more errors can happen.
Did you solve your problem yourself?

**Comment by rafalohaki** [comment]
Ye, i ran it via runtime. But i guess its a problem with php 8.1 version
https://github.com/juicyfx/vercel-examples/tree/master/php/api

https://github.com/vercel-community/php
you can play with it and should work great
no need any php paid hostings if u can host it for free on vercel for example
